version: '3.7'

services:
  project:
    build: .
    container_name: project_app
    command: /bin/sh -c "uvicorn project.api.main:app --host '0.0.0.0' --port 8080"
    environment:
      - WAIT_HOSTS=project_mysql:3306
      - DB_HOST=project_mysql
      - DB_USER=root
      - DB_PORT=3306
      - DB_DATABASE=projectdb
      - DB_PASSWORD=password
      - DB_CONNECTION_POOL_SIZE=5
      - DB_CONNECTION_POOL_MAX_OVERFLOW=10
      - DB_CONNECTION_POOL_TIMEOUT=30
      - DB_CONNECTION_POOL_RECYCLE=3600
      - PYTHONPATH=.
      - ENVIRONMENT=dev
      - SECRET_KEY=e9e9cb2717a5622d690aa661909de0f84986e3a2148dd828fab08d5b51d13a4d
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
    volumes:
      - ./project:/app/project
      - ./test:/app/test
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./Makefile:/app/Makefile
      - ./mypy.ini:/app/mypy.ini
    ports:
      - "8080:8080"
